language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "VDZ7V9V1chpTem93NebIQmrrv0zO+tKkJdQ1wn5KEQOC6u1QmooVtou0s9ScJAu3ZA9FPkdMldmnU+8TOZM9GGzYl9zlIPTFidBl/Y2UKnApP0TRazZwj/gbhpiD3RPyArvUxd3pezcxb+9ToVE8MJeinppYhLwl7wFfr01kI8rvIpNxUJj4r8JM2TQcZlLaHi0DOxpmhHcIP8C/Z/OMSVjHm2WMyfNcUu2fikdKTghkKtTQY0tEr3V9vxXR09nHWtbn3CmnFPmrKGyeZyyqqtjTStVViZUudEYklr7dZpFXJkJVSuMY+KosjxqyVdbn95rFLINQG5LubExwJ2ZC+QWa5zwicZ7NOngBfFFimH8XbdnesJgyOBWZDKYSoeTbhZTJ4e6Ec9OTgXmZdiuDp1zXcy7dIiFAIT29R2cVeJCmOgvH14sxBi4FodfWVuQckNKRQb+sq+JArMQp9jetKez5Ntp+dH9P0t6ktycCMU/vRcLwPoiCPXiCBi9TdG+SejDvre9/o4Rpzg+VAKqL9XdUozlZab874YpF6UC3CMjPy9KU9D3Udaa51w2w1eZzl9LVc0ljYooFBGl4NLTX5m/Y3yVqI9alwSEoWiB4QdLbDIArW5GhmioLjNOkhIvodjG9O4htTuX9LFuJCB+rrDj4+ZNQ7fh77Ew4X6PKfPg="
